#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {runtime,checksum}=require('./regression.cjs');
const root=path.join(__dirname,'..');
const THREE=require(fs.existsSync(path.join(root,'three.min.js'))?path.join(root,'three.min.js'):path.join(root,'src','three.min.js'));
const source=fs.readFileSync(path.join(root,'parts/11_finale.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'parts/06_ui.js'),'utf8');
function setup(rows=[{k:'rooster',n:1},{k:'coon',n:1}],mode='battle'){
 const r=runtime(root),elements=new Map(),results=[];
 const classes=new Set();
 r.c.document={body:{classList:{add:k=>classes.add(k),remove:k=>classes.delete(k),contains:k=>classes.has(k)}}};
 r.c.$=id=>{if(!elements.has(id))elements.set(id,{hidden:false,textContent:'',classList:{remove(){},toggle(){}},focus(){this.focused=true;},addEventListener(k,fn){this[k]=fn;}});return elements.get(id);};
 r.c.THREE=THREE;r.c.camera=new THREE.PerspectiveCamera(46,16/9,.1,500);r.c.camera.position.set(0,24,45);
 r.c.camPos=r.c.camera.position.clone();r.c.camAim=new THREE.Vector3();
 r.c.hideCard=()=>{};r.c.setPhase=()=>{};r.c.highlightFinish=()=>{};
 r.c.showVerdict=(who,how)=>results.push({who,how});
 r.eval(source+ui.slice(ui.indexOf('function verdict('),ui.indexOf('function showVerdict(')));
 r.eval(`bootTest(${JSON.stringify(rows)},7,[],${JSON.stringify(mode)})`);
 return {r,elements,results,classes};
}
const normal=setup(),r=normal.r;
r.eval('hurt(1,100000,0,false)');assert.equal(r.eval('FINALE.deaths[1].i'),1,'real death hook records final predator');
const before=checksum(r),time=r.eval('BATTLE.t'),tick=r.eval('BATTLE.tick');
r.eval("seedSim(876);var expectedRandom=SR();seedSim(876);verdict('birds','The flock holds the field')");
assert.equal(r.eval('FINALE.active'),true);assert.equal(r.eval('BATTLE.over&&!BATTLE.running'),true);
assert.equal(normal.results.length,0,'result card is deferred');assert.ok(normal.classes.has('finishing'));
r.eval("verdict('birds','Duplicate')");assert.equal(normal.results.length,0,'duplicate verdict does not bypass the finish');
r.eval('stepFinale(1.2);finaleCamera()');assert.ok(r.c.camera.position.distanceTo(new THREE.Vector3(r.eval('A.x[1]'),.6,r.eval('A.z[1]')))<15,'camera reaches a close framing');
assert.ok(r.eval('finaleDeathTime()>0&&finaleDeathTime()<.2'),'separate clock plays the fall slowly');
r.eval('stepFinale(2.5)');assert.equal(normal.results.length,1);assert.equal(r.eval('FINALE.active'),false);assert.equal(r.eval('FINALE.hold'),true);
r.eval('finishFinale();stepFinale(10)');assert.equal(normal.results.length,1,'completion only happens once');
assert.equal(r.eval('SR()===expectedRandom'),true,'cinematic does not consume simulation randomness');
assert.equal(checksum(r).hash,before.hash,'finish does not move/heal/kill simulation units');
assert.equal(r.eval('BATTLE.tick'),tick);assert.equal(r.eval('BATTLE.t'),time);
r.eval('resetFinale()');assert.equal(r.eval('FINALE.target'),null);assert.equal(r.eval('FINALE.hold'),false);
assert.equal(normal.elements.get('finaleBanner').hidden,true,'new raid clears overlay and held camera');
console.log('PASS real death hook, frozen outcome/tick/RNG, slow visual clock, close camera, deferred/single result and reset');
const skip=setup();skip.r.eval("hurt(0,100000,1,false);verdict('coons','Total poultry failure');initFinaleUI()");
assert.equal(skip.r.eval('FINALE.target.i'),0,'defender elimination tracks the losing side');
skip.elements.get('finaleSkip').click({stopPropagation(){}});assert.equal(skip.results.length,1,'skip button reveals results');
const hen=setup(undefined,'defense');hen.r.eval("COOP.hens[0].hp=0;COOP.hens[1].hp=1;A.cd[1]=0;coopStrike(1,COOP.hens[1],true);verdict('coons','Both hens were lost')");
assert.equal(hen.r.eval('FINALE.target.type'),'hen');assert.equal(hen.r.eval('FINALE.target.i'),1);assert.equal(hen.r.eval('finaleSubject("hen",1)'),true);
const reduced=setup();reduced.r.eval("VIEW.reducedMotion=true;hurt(1,100000,0,false);verdict('birds','Won');stepFinale(.4);finaleCamera()");
assert.deepEqual(reduced.r.c.camera.position.toArray(),[0,24,45],'reduced motion preserves framing');
reduced.r.eval('stepFinale(.41)');assert.equal(reduced.results.length,1,'reduced motion has a shorter hold');
const seek=setup();seek.r.eval("hurt(1,100000,0,false);REPLAY.seeking=true;verdict('birds','Won')");assert.equal(seek.results.length,1);assert.equal(seek.r.eval('FINALE.active'),false,'fast seeking cannot stall on cinematic');
const noDeath=setup();noDeath.r.eval("verdict('birds','Called on time')");assert.equal(noDeath.results.length,1);assert.equal(noDeath.r.eval('FINALE.active'),false,'non-elimination verdict has no invented death');
const possum=setup([{k:'rooster',n:1},{k:'possum',n:1}]);possum.r.eval('hurt(1,100000,0,false)');assert.equal(possum.r.eval('A.rev[1]'),2);assert.equal(possum.r.eval('FINALE.deaths[1]'),null,'playing dead cannot trigger the finish');
console.log('PASS defender/hen targeting, skip, reduced motion, seeking, non-death outcomes and fake-dead possum');
